version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'jdbc-template-postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app_crud_jdbc_template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data:
